export const services = [
  {
    id: 'solar-panels',
    name: 'Solar Panels',
    icon: '☀️',
    description: 'Professional solar panel installation for residential and commercial properties in Luxembourg.',
    features: ['Creos subsidy support', 'Energy savings', 'Eco-friendly'],
  },
  {
    id: 'ev-chargers',
    name: 'EV Chargers',
    icon: '🔌',
    description: 'Electric vehicle charging station installation with full Creos subsidy compliance.',
    features: ['Fast charging', 'Smart integration', 'Government subsidies'],
  },
  {
    id: 'heat-pumps',
    name: 'Heat Pumps',
    icon: '🌡️',
    description: 'Energy-efficient heat pump systems for sustainable heating and cooling.',
    features: ['Energy efficient', 'Year-round comfort', 'Low maintenance'],
  },
  {
    id: 'energy-audits',
    name: 'Energy Audits',
    icon: '📊',
    description: 'Comprehensive energy assessments to optimize your property efficiency.',
    features: ['Detailed analysis', 'Cost savings', 'Improvement plan'],
  },
  {
    id: 'electrician',
    name: 'Electrician Services',
    icon: '⚡',
    description: 'Licensed electrical services for installations, repairs, and maintenance.',
    features: ['24/7 emergency', 'Licensed professionals', 'Quality guaranteed'],
  },
  {
    id: 'air-conditioning',
    name: 'Air Conditioning',
    icon: '❄️',
    description: 'Professional AC installation and maintenance services.',
    features: ['Energy efficient', 'Quiet operation', 'Expert installation'],
  },
  {
    id: 'home-automation',
    name: 'Home Automation',
    icon: '🏠',
    description: 'Smart home solutions for modern, connected living.',
    features: ['Voice control', 'Energy monitoring', 'Remote access'],
  },
  {
    id: 'security-systems',
    name: 'Security & Alarm Systems',
    icon: '🔒',
    description: 'Advanced security and alarm systems for your property protection.',
    features: ['24/7 monitoring', 'Smart alerts', 'Professional installation'],
  },
  {
    id: 'maintenance',
    name: 'Maintenance Services',
    icon: '🔧',
    description: 'Regular maintenance and support for all electrical systems.',
    features: ['Preventive care', 'Quick response', 'Long-term support'],
  },
];